// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S4U.Persistance.Contexts;

namespace S4U.Persistance.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20201129154225_Prices")]
    partial class Prices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("S4U.Domain.Entities.CompareEquity", b =>
                {
                    b.Property<Guid>("UserID");

                    b.Property<Guid>("EquityID");

                    b.Property<Guid>("CompareID");

                    b.HasKey("UserID", "EquityID", "CompareID");

                    b.HasAlternateKey("CompareID", "UserID");

                    b.HasIndex("UserID", "EquityID", "CompareID");

                    b.ToTable("CompareEquities");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Equity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Id", "Ticker");

                    b.ToTable("Equities");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Alert");

                    b.Property<string>("Attach")
                        .HasMaxLength(256);

                    b.Property<string>("Comments")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("EquityID");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserID", "EquityID");

                    b.HasIndex("Id", "UserID", "EquityID", "Alert");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("RedirectID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.HasIndex("Id", "UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PaymentType");

                    b.Property<Guid?>("PlanId");

                    b.Property<Guid?>("SignatureId");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("SignatureId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descyption")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("Id", "Name");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Id", "Name");

                    b.ToTable("Roles");

                    b.HasData(
                        new { Id = new Guid("a8fe4874-562f-4f4a-9f83-6b47fce6792d"), Name = "Administrator" },
                        new { Id = new Guid("d06ada51-cfd0-463b-a855-ce7c9dbe8d63"), Name = "Client" }
                    );
                });

            modelBuilder.Entity("S4U.Domain.Entities.Signature", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<DateTime>("ExpiredDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid>("PlanID");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("PlanID");

                    b.ToTable("Signatures");
                });

            modelBuilder.Entity("S4U.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("BirthDate");

                    b.Property<string>("Compliment")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Gender")
                        .HasMaxLength(11);

                    b.Property<string>("Image")
                        .HasMaxLength(256);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Number")
                        .HasMaxLength(6);

                    b.Property<string>("PushToken");

                    b.Property<Guid>("RoleID");

                    b.Property<Guid?>("SignatureID");

                    b.HasKey("Id");

                    b.HasIndex("RoleID");

                    b.HasIndex("Id", "Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("S4U.Domain.Entities.UserEquity", b =>
                {
                    b.Property<Guid>("UserID");

                    b.Property<Guid>("EquityID");

                    b.HasKey("UserID", "EquityID");

                    b.HasAlternateKey("EquityID", "UserID");

                    b.HasIndex("UserID", "EquityID");

                    b.ToTable("UserEquities");
                });

            modelBuilder.Entity("S4U.Domain.Entities.UserEquityPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("Deleted");

                    b.Property<Guid>("EquityID");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<double>("Price");

                    b.Property<bool>("Sent");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<Guid>("UserID");

                    b.HasKey("Id");

                    b.HasIndex("UserID", "EquityID");

                    b.HasIndex("Id", "UserID", "EquityID");

                    b.ToTable("UserEquityPrices");
                });

            modelBuilder.Entity("S4U.Domain.Entities.CompareEquity", b =>
                {
                    b.HasOne("S4U.Domain.Entities.Equity", "Equity")
                        .WithMany("EquitiesThatCompare")
                        .HasForeignKey("CompareID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("S4U.Domain.Entities.UserEquity", "UserEquity")
                        .WithMany("EquitiesToCompare")
                        .HasForeignKey("UserID", "EquityID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("S4U.Domain.Entities.Note", b =>
                {
                    b.HasOne("S4U.Domain.Entities.UserEquity", "UserEquity")
                        .WithMany("Notes")
                        .HasForeignKey("UserID", "EquityID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("S4U.Domain.Entities.Notification", b =>
                {
                    b.HasOne("S4U.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("S4U.Domain.Entities.Payment", b =>
                {
                    b.HasOne("S4U.Domain.Entities.Plan")
                        .WithMany("Payments")
                        .HasForeignKey("PlanId");

                    b.HasOne("S4U.Domain.Entities.Signature")
                        .WithMany("Payments")
                        .HasForeignKey("SignatureId");
                });

            modelBuilder.Entity("S4U.Domain.Entities.Signature", b =>
                {
                    b.HasOne("S4U.Domain.Entities.User", "User")
                        .WithOne("Signature")
                        .HasForeignKey("S4U.Domain.Entities.Signature", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("S4U.Domain.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("S4U.Domain.Entities.User", b =>
                {
                    b.HasOne("S4U.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("S4U.Domain.Entities.UserEquity", b =>
                {
                    b.HasOne("S4U.Domain.Entities.Equity", "Equity")
                        .WithMany("UsersEquities")
                        .HasForeignKey("EquityID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("S4U.Domain.Entities.User", "User")
                        .WithMany("UsersEquities")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("S4U.Domain.Entities.UserEquityPrice", b =>
                {
                    b.HasOne("S4U.Domain.Entities.UserEquity", "UserEquity")
                        .WithMany("Prices")
                        .HasForeignKey("UserID", "EquityID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
